image:
  file: .gitpod.Dockerfile

workspaceLocation: "."

# This will expose all necessary ports needed for your VNC image
ports:
  - port: 5080
    onOpen: open-preview
  - port: 6379
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 8080
    onOpen: ignore

# This will make it so that on workspace start it will run a file called `app.py`
tasks:
  - init: pip3 install -r requirements.txt
  - command: find ./ -iname "*.sh" -exec chmod +x {} +

vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - formulahendry.auto-close-tag@0.5.9:JZIefALANqOfhSK1TU4+Fw==