image:
  file: .gitpod.Dockerfile

# location to open in code editor explorer
workspaceLocation: "."
checkoutLocation: "."

# This will expose all necessary ports
ports:
  - port: 8000
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 8888
    onOpen: open-browser

# commands to run
tasks:
  - before: find ./ -iname "*.sh" -exec chmod +x {} +
    init: cd /workspace/gitpod-python-template && ./run.sh && cd /workspace
    command: python --version
  - command: |
      cd /workspace
      cp -r gitpod-python-template/.jupyter /home/gitpod/
      cp -r gitpod-python-template/.theia /workspace

# vscode extension to install for project
vscode:
  extensions:
    - formulahendry.auto-close-tag@0.5.9:JZIefALANqOfhSK1TU4+Fw==